### ISSUE TITLE
论坛没号，所以用issue打扰下哈

### ISSUE THREAD

**Issue by ted423** [naivekun/wd_an1500_mod#2]
我买了一个玩了一下。好像刷写没成功。
lspci -vvvv 其中 Expansion ROM 显示的还是disable ,按我理解 option ROM是没enable?
另外readme 里的 1 2 3应该不是顺序的步骤？我只跑了第一步。

后面准备force 刷 20241107_mod.bin试试

**Comment by ted423** [comment]
force的脚本似乎有问题，cd进去了，应该是要用上一层目录的文件，手动跑了下命令应该是可以的

**Comment by naivekun** [comment]
确实，mvf工具需要当前目录里面有spilist.bin文件，所以cd进去了

**Comment by naivekun** [comment]
fixed

**Comment by ted423** [comment]
好像是没成功，server认的还是nvme device.
不清楚会不会是主板兼容性问题
