### ISSUE TITLE
想备份卡上本来的西数固件就遇到了错误

### ISSUE THREAD

**Issue by monsoon7ice** [naivekun/wd_an1500_mod#3]
Cannot map to any memory BAR. Wrong (0)!
Cannot map to any memory BAR. Wrong (0)!
Cannot map to any memory BAR.
No Adapter Found.

**各位有什么好点子吗？**

**Comment by Hotinosin** [comment]
我在使用 mnc_cli 刷入固件之后，能在mnc_cli info中看到已刷入JBOD模式，但是重启进 bios，还是看不到相关的选项，后面尝试使用 mvf 强刷固件的时候，也出现了这个报错

**Comment by monsoon7ice** [comment]
> Cannot map to any memory BAR. Wrong (0)! Cannot map to any memory BAR. Wrong (0)! Cannot map to any memory BAR. No Adapter Found.
> 
> **各位有什么好点子吗？**

确认了一下，在ubuntu 24.04系统内可以lspci确认到有阵列卡信息，而且阵列后的raid0磁盘可以正常使用；就是试图备份固件会出错哦。

**Comment by naivekun** [comment]
这个错误是因为无法访问/dev/mem导致的，需要你修改/etc/default/grub,在内核commandline后面加iomem=relaxed,然后update-grub再重启

**Comment by monsoon7ice** [comment]
> 这个错误是因为无法访问/dev/mem导致的，需要你修改/etc/default/grub,在内核commandline后面加iomem=relaxed,然后update-grub再重启

谢谢你的回复，我准备过几天做出改动后再尝试一下~

**Comment by monsoon7ice** [comment]
> 这个错误是因为无法访问/dev/mem导致的，需要你修改/etc/default/grub,在内核commandline后面加iomem=relaxed,然后update-grub再重启

之前重新尝试，在内核commandline后面加iommu=relaxed，更新grub；还是无法备份固件，但可以用./flash_fw.sh ./an1500_backup_20241107_mod.bin刷入固件。

**Comment by monsoon7ice** [comment]
> 这个错误是因为无法访问/dev/mem导致的，需要你修改/etc/default/grub,在内核commandline后面加iomem=relaxed,然后update-grub再重启

已在我的设备上解决，具体操作是主板UEFI设置内关闭的安全启动就不再出现该错误。

**Comment by monsoon7ice** [comment]
> 我在使用 mnc_cli 刷入固件之后，能在mnc_cli info中看到已刷入JBOD模式，但是重启进 bios，还是看不到相关的选项，后面尝试使用 mvf 强刷固件的时候，也出现了这个报错

已在我的设备上解决，具体操作是主板UEFI设置内关闭的安全启动就不再出现该错误。
